export async function exportProtocolToPDF(
  patientName: string = 'Patient',
  diagnosis: string = ''
): Promise<void> {
  const element = document.getElementById('protocol-document')
  if (!element) {
    console.error('[PDF] No protocol document element found')
    return
  }

  // Dynamically import html2pdf.js (client-side only)
  const html2pdf = (await import('html2pdf.js')).default

  const date = new Date().toISOString().split('T')[0]
  const safeName = patientName.replace(/[^a-zA-Z0-9\s]/g, '').trim() || 'Patient'
  const filename = `treatment-protocol-${safeName.replace(/\s+/g, '-')}-${date}.pdf`

  // Create a clone for PDF rendering with light theme
  const clone = element.cloneNode(true) as HTMLElement

  // Apply print-optimized styles
  clone.style.cssText = `
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    color: #1a1a1a;
    background: #ffffff;
    padding: 20px;
    line-height: 1.6;
  `

  // Style all prose content for light theme
  const allElements = clone.querySelectorAll('*')
  for (const el of allElements) {
    const htmlEl = el as HTMLElement
    if (htmlEl.style) {
      htmlEl.style.color = '#1a1a1a'
    }
  }

  // Style headings
  const headings = clone.querySelectorAll('h1, h2, h3, h4')
  for (const h of headings) {
    const htmlH = h as HTMLElement
    htmlH.style.color = '#0a0a0a'
    htmlH.style.fontWeight = '700'
  }

  // Style tables
  const tables = clone.querySelectorAll('table')
  for (const t of tables) {
    t.style.cssText = 'width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 12px;'
    const cells = t.querySelectorAll('th, td')
    for (const c of cells) {
      const htmlC = c as HTMLElement
      htmlC.style.cssText = 'border: 1px solid #d1d5db; padding: 8px; text-align: left;'
      if (c.tagName === 'TH') {
        htmlC.style.background = '#f3f4f6'
        htmlC.style.fontWeight = '600'
      }
    }
  }

  // Style links
  const links = clone.querySelectorAll('a')
  for (const a of links) {
    a.style.color = '#2563eb'
    a.style.textDecoration = 'underline'
  }

  // Style section cards
  const sections = clone.querySelectorAll('.protocol-section')
  for (const s of sections) {
    const htmlS = s as HTMLElement
    htmlS.style.background = '#f9fafb'
    htmlS.style.borderLeftColor = '#6366f1'
    htmlS.style.borderRadius = '8px'
    htmlS.style.marginBottom = '16px'
    htmlS.style.padding = '16px'
    htmlS.style.pageBreakInside = 'avoid'
  }

  // Create wrapper with header and footer
  const wrapper = document.createElement('div')
  wrapper.style.cssText = 'font-family: Segoe UI, system-ui, sans-serif; color: #1a1a1a; background: #fff;'

  // Header
  const header = document.createElement('div')
  header.style.cssText = 'text-align: center; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #6366f1;'
  header.innerHTML = `
    <h1 style="font-size: 20px; font-weight: 700; color: #0a0a0a; margin: 0 0 4px 0;">
      AyurVritta Clinical AI
    </h1>
    <p style="font-size: 14px; color: #6b7280; margin: 0 0 4px 0;">
      Treatment Protocol — Clinical Case Study
    </p>
    <p style="font-size: 12px; color: #9ca3af; margin: 0;">
      Patient: ${safeName} | Date: ${date} ${diagnosis ? `| Diagnosis: ${diagnosis}` : ''}
    </p>
  `
  wrapper.appendChild(header)
  wrapper.appendChild(clone)

  // Footer disclaimer
  const footer = document.createElement('div')
  footer.style.cssText = 'margin-top: 24px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center;'
  footer.innerHTML = `
    <p style="margin: 0 0 4px 0;">
      This protocol is AI-generated and intended as a clinical decision support tool. It must be reviewed and approved by a qualified Ayurvedic physician before implementation.
    </p>
    <p style="margin: 0;">
      Generated by AyurVritta Clinical AI | ${date} | Page <span class="pageNumber"></span> of <span class="totalPages"></span>
    </p>
  `
  wrapper.appendChild(footer)

  const opt: Record<string, unknown> = {
    margin: [15, 15, 20, 15],
    filename,
    image: { type: 'jpeg', quality: 0.95 },
    html2canvas: {
      scale: 2,
      useCORS: true,
      letterRendering: true,
      logging: false,
    },
    jsPDF: {
      unit: 'mm',
      format: 'a4',
      orientation: 'portrait',
    },
    pagebreak: {
      mode: ['avoid-all', 'css', 'legacy'],
      before: '.protocol-section',
      avoid: ['table', 'tr', '.protocol-section'],
    },
  }

  try {
    await html2pdf().set(opt).from(wrapper).save()
  } catch (error) {
    console.error('[PDF] Export failed:', error)
    throw error
  }
}
