// Charak Samhita - Sutra Sthana (30 Chapters)
// Section on Fundamental Principles of Ayurveda
// Source: carakasamhitaonline.com (CC BY-NC-SA 4.0)

import type { CharakChapter } from './types'

export const SUTRA_STHANA: CharakChapter[] = [
  {
    id: 'sutra_ch1',
    sthana: 'Sutra Sthana',
    chapterNumber: 1,
    name: 'Deerghanjiviteeya Adhyaya',
    english: 'Chapter on Longevity',
    summary: 'Foundation chapter covering origin of Ayurveda, definition of Ayu, Tridosha basics, Shad Padartha (six fundamental principles), Rasa (taste) classification, Dravya (substance) classification, and ethical principles of clinical practice. Establishes the tri-sutra of Ayurveda: Hetu (etiology), Linga (symptomatology), Aushadha (therapeutics).',
    keyConcepts: [
      'Ayurveda defined as knowledge of hita-ahita (wholesome/unwholesome), sukha-duhkha (happiness/sorrow), and ayu (life)',
      'Ayu = conjunction of Sharira (body), Indriya (senses), Satva (mind), and Atma (soul)',
      'Three Sharira Dosha: Vata, Pitta, Kapha; Two Manas Dosha: Rajas, Tamas',
      'Six Padartha: Samanya (similarity), Vishesha (dissimilarity), Guna (properties), Dravya (substances), Karma (action), Samavaya (inseparable concomitance)',
      'Samanya causes increase, Vishesha causes decrease of all elements',
      'Six Rasa (tastes): Madhura (sweet), Amla (sour), Lavana (salty), Tikta (bitter), Katu (pungent), Kashaya (astringent)',
      'Vata properties: Ruksha (dry), Sheeta (cold), Laghu (light), Sukshma (subtle), Chala (mobile), Vishada (non-slimy), Khara (rough)',
      'Pitta properties: Sasneha (slightly unctuous), Ushna (hot), Tikshna (sharp), Drava (liquid), Amla (sour), Sara (mobile), Katu (pungent)',
      'Kapha properties: Guru (heavy), Sheeta (cold), Mrudu (soft), Snigdha (unctuous), Madhura (sweet), Sthira (stable), Pichchhila (slimy)',
      'Diseases treated with drugs having opposite properties (Viparita Guna)',
      'Four objectives of life: Dharma (virtue), Artha (wealth), Kama (gratification), Moksha (emancipation)',
      'Health (Arogya) is the root of all four objectives',
      'Trisutra: Hetu-Linga-Aushadha knowledge is for both Swastha (healthy) and Atura (sick)',
      'Best physician has full knowledge of drugs, pharmacology, and personalized medicine',
    ],
    shlokas: [
      { number: '1.41', translation: 'Ayurveda deals with wholesome and unwholesome, happy and sorrowful life, and what is beneficial and harmful for longevity.' },
      { number: '1.42', translation: 'Ayu (life) is the conjunction of body, senses, mind, and soul.' },
      { number: '1.44', translation: 'Samanya (similarity) is the cause of increase and Vishesha (dissimilarity) is the cause of decrease of all elements.' },
      { number: '1.54', translation: 'Erroneous use, avoidance, and excessive use of time, intellect, and sense objects is the threefold cause of all diseases.' },
      { number: '1.55', translation: 'Both body and mind are the sites of disease and pleasure. Balanced use is the cause of health.' },
      { number: '1.57', translation: 'Vata, Pitta, and Kapha are the three bodily dosha; Rajas and Tamas are the mental dosha.' },
      { number: '1.58', translation: 'Bodily dosha are pacified by medicines and rational therapy; mental dosha by knowledge, wisdom, patience, memory, and meditation.' },
      { number: '1.59-61', translation: 'Vata is dry, cold, light, subtle, mobile - pacified by opposite qualities. Pitta is unctuous, hot, sharp, liquid - pacified by opposite qualities. Kapha is heavy, cold, soft, unctuous, sweet - pacified by opposite qualities.' },
      { number: '1.62', translation: 'Curable diseases are treated with drugs having opposite properties, considering place, dosage, and time.' },
    ],
    doshaDiscussion: [
      'Vata: Ruksha (dry), Sheeta (cold), Laghu (light), Sukshma (subtle), Chala (mobile), Vishada (non-slimy), Khara (rough) - pacified by Snigdha (unctuous), Guru (heavy) substances',
      'Pitta: Sasneha (slightly oily), Ushna (hot), Tikshna (sharp), Drava (liquid), Amla (sour), Sara (flowing), Katu (pungent) - pacified by Sheeta (cold), Madhura (sweet) substances',
      'Kapha: Guru (heavy), Sheeta (cold), Mrudu (soft), Snigdha (unctuous), Madhura (sweet), Sthira (stable), Pichchhila (slimy) - pacified by Tikshna (sharp), Ruksha (dry) substances',
      'Treatment principle: Like increases like (Samanya), opposite pacifies (Vishesha)',
    ],
    treatmentPrinciples: [
      'Treatment uses drugs with Viparita Guna (opposite qualities) to the dosha',
      'Consider Desha (place), Matra (dosage), and Kala (time) in treatment',
      'Curable diseases (Sadhyas) should be treated; incurable diseases should not be attempted',
      'Three treatment approaches: Daivavyapashraya (divine), Yuktivyapashraya (rational), Satvavajaya (psychological)',
    ],
    dietaryGuidelines: [],
    clinicalApplications: [
      'Foundation for understanding Tridosha pathology',
      'Samanya-Vishesha principle guides all treatment decisions',
      'Classification of drugs based on source (animal, plant, mineral)',
      'Ethical guidelines for physician conduct',
    ],
    topics: [
      { title: 'Origin of Ayurveda', content: 'Brahma -> Prajapati -> Ashvini Kumaras -> Indra -> Bharadwaja -> Sages -> Agnivesha and disciples' },
      { title: 'Dravya Classification', content: '16 roots for Shodhana, fruits for Shodhana, 4 Mahasneha (ghee, oil, muscle fat, marrow), 5 salts, 8 types of urine, 8 types of milk' },
      { title: 'Qualities of Best Physician', content: 'Full knowledge of drugs, pharmacology, mode of administration, use according to patient condition. Exploitation of patients is sinful.' },
    ],
  },
  {
    id: 'sutra_ch5',
    sthana: 'Sutra Sthana',
    chapterNumber: 5,
    name: 'Matrashiteeya Adhyaya',
    english: 'Chapter on Proper Quantity of Food and Daily Regimen',
    summary: 'Covers proper quantity of diet based on Agni strength, inherently heavy and light foods, daily regimen including collyrium, dhumapana (smoking), nasya, oral hygiene, abhyanga, and snana.',
    keyConcepts: [
      'Matra (proper quantity) depends on Agni (digestive power)',
      'Food digested in due time without disturbing normalcy = proper quantity',
      'Light foods (Laghu): Shali rice, Shashtika rice, Mudga (green gram), quail, partridge, antelope, rabbit',
      'Heavy foods (Guru): flour preparations, sugarcane, milk products, sesame, black gram, marshy/aquatic meat',
      'Light foods have Vayu-Agni predominance, stimulate Agni, less harmful even in excess',
      'Heavy foods have Prithvi-Jala predominance, don\'t stimulate Agni, harmful in excess',
      'Heavy foods: take only 1/3 to 1/2 of stomach capacity',
      'Regular intake: Shashtika rice, Shali rice, Mudga, Saindhava salt, Amalaka, Yava (barley), milk, ghee, Jangala meat, honey',
      'Forbidden habitual intake: dried meat, dried vegetables, lotus tubers, emaciated meat, pork, cow/buffalo meat, fish, curd, black gram',
      'Eight times for Dhumapana: after bath, after eating, after tongue scraping, after sneezing, after teeth cleaning, after nasya, after collyrium, after sleep',
      'Three types of Dhumapana: Prayogika (daily), Snaihika (unctuous), Vairechanika (purgative)',
      'Dhumapana contraindications: after virechana, basti, in pregnancy, fatigue, intoxication, pitta disorders, thirst, emaciation',
    ],
    shlokas: [
      { number: '5.3', translation: 'One must take food in proper quantity, which depends on the strength of Agni.' },
      { number: '5.4', translation: 'Proper quantity is that which is digested in due time without disturbing normalcy.' },
      { number: '5.6', translation: 'Light foods stimulate Agni; heavy foods do not. Excess heavy food causes harm unless strong Agni through exercise.' },
      { number: '5.8', translation: 'Food taken in right quantity provides strength, complexion, happiness, and longevity.' },
      { number: '5.12', translation: 'Regularly consume Shashtika rice, Shali rice, Mudga, rock salt, Amalaka, barley, rain water, milk, ghee, Jangala meat, and honey.' },
    ],
    doshaDiscussion: [
      'Vata-Kapha aggravation occurs at specific times - Dhumapana prevents upper body diseases',
      'Eye is Tejomaya (fire element) - susceptible to Kapha vitiation',
      'Dhumapana pacifies Vata-Kapha in Urdhva Jatru (head region)',
    ],
    treatmentPrinciples: [
      'Nasya (nasal therapy) with Anu Taila for head diseases',
      'Dhumapana for Kapha-Vata disorders above clavicle',
      'Gandusha (oil gargling) for oral health',
      'Abhyanga (massage) for Vata pacification and strength',
    ],
    dietaryGuidelines: [
      'Never eat heavy foods on top of a meal',
      'Even when hungry, take heavy foods in right quantity',
      'One-third of stomach for food, one-third for liquid, one-third empty',
      'Eat warm, unctuous, in proper quantity, at proper time',
    ],
    clinicalApplications: [
      'Dinacharya (daily regimen) foundation',
      'Dietary counseling based on Agni assessment',
      'Dhumapana therapy for upper respiratory conditions',
      'Nasya for ENT and neurological conditions',
    ],
    topics: [
      { title: 'Diet Quantity', content: 'Depends on Agni strength. Heavy foods: 1/3-1/2 capacity. Light foods: not to excess either.' },
      { title: 'Dhumapana', content: 'Three types with 3 puffs each. Prayogika twice daily, Snaihika once, Vairechanika 3-4 times.' },
      { title: 'Daily Regimen', content: 'Collyrium, dhumapana, nasya, tooth cleaning, tongue scraping, oil gargling, massage, bath, clean clothes.' },
    ],
  },
  {
    id: 'sutra_ch6',
    sthana: 'Sutra Sthana',
    chapterNumber: 6,
    name: 'Tasyashiteeya Adhyaya',
    english: 'Chapter on Seasonal Regimen',
    summary: 'Details Ritucharya (seasonal regimen) and Dinacharya (daily regimen). Explains how seasonal changes affect dosha and the specific lifestyle adjustments needed for each season to maintain health.',
    keyConcepts: [
      'Six seasons: Shishira (winter), Vasanta (spring), Grishma (summer), Varsha (monsoon), Sharad (autumn), Hemanta (late autumn)',
      'Adana Kala (northern solstice): Vata-Pitta increase, body strength decreases',
      'Visarga Kala (southern solstice): Kapha increase, body strength increases',
      'Ritu Sandhi: 14-day transition period between seasons - continue previous season regimen',
      'Dinacharya: Brahma Muhurta waking, evacuation, brushing, tongue scraping, oil gargling, nasya, eye care, abhyanga, exercise, bath',
      'Brahma Muhurta (1.5 hours before sunrise) is best time to wake',
      'Abhyanga daily for: reducing aging, Vata, fatigue; improving vision, sleep, skin',
      'Exercise to 50% capacity - half of one\'s strength',
      'Shiro Abhyanga (head oil) prevents headache, hair fall, graying',
      'Padabhyanga (foot massage) prevents cracking, stiffness, sciatica',
    ],
    shlokas: [
      { number: '6.1', translation: 'We shall expound Tasyashiteeya (wholesome and unwholesome regimen for seasons).' },
    ],
    doshaDiscussion: [
      'Shishira: Kapha accumulates, Vata begins to aggravate',
      'Vasanta: Kapha aggravates - use Tikta, Kashaya, Laghu foods; avoid Guru, Snigdha, Madhura',
      'Grishma: Pitta accumulates, strength decreases - use Madhura, Sheeta, Snigdha; cold water bath',
      'Varsha: Vata aggravates, Agni weak - use Amla, Lavana, Snigdha; avoid exercise',
      'Sharad: Pitta aggravates - use Madhura, Tikta, Sheeta; avoid Katu, Amla, Ushna',
      'Hemanta: Strong Agni, Kapha accumulates - use Guru, Snigdha, Amla, Lavana; massage and fomentation',
    ],
    treatmentPrinciples: [
      'Seasonal purification (Shodhana) at Ritu Sandhi',
      'Virechana in Vasanta for Kapha',
      'Basti in Varsha for Vata',
      'Vamana in Pravrit (early rainy) for Kapha',
    ],
    dietaryGuidelines: [
      'Vasanta: Laghu, Tikta, Kashaya; avoid curd, oil, heavy foods',
      'Grishma: Cold, liquid, Madhura; avoid exercise, alcohol',
      'Varsha: Warm, dry foods; avoid rivers, day sleep',
      'Sharad: Madhura, Sheeta, Laghu; avoid heavy exercise',
      'Hemanta: Heavy, unctuous, warm foods; sesame oil massage',
    ],
    clinicalApplications: [
      'Seasonal disease prevention',
      'Ritucharya-based lifestyle counseling',
      'Seasonal Panchakarma scheduling',
      'Climate-adaptive treatment planning',
    ],
    topics: [
      { title: 'Seasonal Regimen', content: 'Six seasons with specific diet, lifestyle, and purification for each.' },
      { title: 'Daily Regimen', content: 'Detailed Dinacharya from waking to sleeping.' },
    ],
  },
  {
    id: 'sutra_ch13',
    sthana: 'Sutra Sthana',
    chapterNumber: 13,
    name: 'Snehadhyaya',
    english: 'Chapter on Oleation Therapy',
    summary: 'Comprehensive coverage of Snehana (oleation) - internal and external use of unctuous substances. Covers four Mahasneha (ghee, oil, muscle fat, marrow), their properties, indications, and methods of administration.',
    keyConcepts: [
      'Four Mahasneha: Ghrita (ghee), Taila (oil), Vasa (musfat), Majja (marrow)',
      'Ghrita: best for Pitta disorders, Rakta disorders, Visha (poisoning), burns',
      'Taila: best for Vata disorders, skin diseases, Krimi (worms)',
      'Vasa: useful for Vata disorders, fractures, ligament injuries',
      'Majja: best for Vata-Kapha disorders, emaciation, debility',
      'Snehana (oleation) is of two types: internal (Snehapana) and external (Abhyanga)',
      'Snehapana: oral intake of medicated ghee/oil in increasing doses',
      'Agnimandya (weak Agni) is the primary contraindication for Snehapana',
      'Sneha is absorbed through Rasa Dhatu and reaches all Dhatus',
    ],
    shlokas: [],
    doshaDiscussion: [
      'Ghrita pacifies Pitta and Vata',
      'Taila pacifies Vata',
      'All Sneha increase Kapha if not properly digested',
      'Snehana prepares body for Shodhana (purification)',
    ],
    treatmentPrinciples: [
      'Snehapana before Shodhana Karma',
      'Matra (dose) depends on Agni and disease',
      'Koshtha assessment for dose determination',
      'Signs of proper Snehana: soft stools, clarity of senses, lightness',
    ],
    dietaryGuidelines: [
      'During Snehapana: light liquid diet initially',
      'After Snehana: specific diet to maintain oleation',
      'Avoid heavy, cold, dry foods during Snehana',
    ],
    clinicalApplications: [
      'Pre-Panchakarma preparation',
      'Vata disorders treatment',
      'Chronic skin disease management',
      'Debility and emaciation treatment',
    ],
    topics: [
      { title: 'Four Mahasneha', content: 'Ghrita, Taila, Vasa, Majja with specific properties and indications.' },
      { title: 'Snehapana Protocol', content: 'Increasing doses over 3-7 days until proper oleation signs appear.' },
    ],
  },
  {
    id: 'sutra_ch14',
    sthana: 'Sutra Sthana',
    chapterNumber: 14,
    name: 'Swedadhyaya',
    english: 'Chapter on Fomentation Therapy',
    summary: 'Details Swedana (fomentation/sudation) therapy - types, indications, contraindications, and methods. Covers all forms of heat therapy used in Ayurveda.',
    keyConcepts: [
      'Swedana is of two main types: Sagni (with fire/fomentation) and Niragni (without fire/exercise, covering)',
      'Sagni Swedana: 13 types including Avagaha (sitz bath), Nadi (tube fomentation), Pinda (bolus fomentation), Prastara (bed fomentation)',
      'Niragni Swedana: exercise, heavy clothing, staying in closed room, exposure to sun',
      'Swedana liquefies Ama and stuck Dosha',
      'Indicated in Vata-Kapha disorders, stiffness, heaviness, coldness',
      'Contraindicated in Pitta disorders, Raktapitta, diabetes, pregnancy, after alcohol',
      'Signs of proper Swedana: sweating, lightness, reduction of pain/stiffness',
      'Signs of excess: thirst, burning, fainting, dizziness',
    ],
    shlokas: [],
    doshaDiscussion: [
      'Swedana primarily pacifies Vata and Kapha',
      'Can aggravate Pitta if excessive',
      'Should not be done in Pitta-predominant conditions',
    ],
    treatmentPrinciples: [
      'Always after Snehana (oleation)',
      'Before Shodhana (purification)',
      'Specific fomentation for specific body parts',
      'Duration depends on disease and patient strength',
    ],
    dietaryGuidelines: [
      'After Swedana: light warm food',
      'Avoid cold food/drinks after fomentation',
    ],
    clinicalApplications: [
      'Joint stiffness and pain',
      'Vata disorders',
      'Kapha accumulation',
      'Pre-Panchakarma preparation',
    ],
    topics: [
      { title: 'Types of Swedana', content: '13 Sagni types + Niragni methods. Selection based on disease and body part.' },
    ],
  },
  {
    id: 'sutra_ch17',
    sthana: 'Sutra Sthana',
    chapterNumber: 17,
    name: 'Kiyanta Shiraseeya Adhyaya',
    english: 'Chapter on Diseases of Head Region',
    summary: 'Classification of diseases starting from Shiroroga (head diseases), their etiology, and treatment principles. Covers the scope of diseases manageable by the physician.',
    keyConcepts: [
      'Diseases are classified by location: Shiras (head), Kantha (throat), Hridaya (heart), Nabhi (navel), Basti (bladder), and other body parts',
      'Shiroroga types: Vataja, Pittaja, Kaphaja, Sannipataja, Krimija, Raktaja',
      'Treatment follows Trisutra: knowledge of cause, symptom, and medicine',
    ],
    shlokas: [],
    doshaDiscussion: [
      'Head diseases classified by predominant dosha',
      'Sannipataja (tridoshic) is most difficult to treat',
    ],
    treatmentPrinciples: [
      'Nasya (nasal therapy) for head diseases',
      'Shirodhara for chronic head conditions',
      'Specific treatment based on dosha involvement',
    ],
    dietaryGuidelines: [],
    clinicalApplications: [
      'Classification of neurological and ENT disorders',
      'Treatment planning for head region diseases',
    ],
    topics: [],
  },
  {
    id: 'sutra_ch18',
    sthana: 'Sutra Sthana',
    chapterNumber: 18,
    name: 'Trishothiya Adhyaya',
    english: 'Chapter on Swelling/Inflammation',
    summary: 'Comprehensive description of Shotha (swelling/inflammation) - types, etiology, pathogenesis, and treatment.',
    keyConcepts: [
      'Shotha classification: Vataja, Pittaja, Kaphaja, Raktaja, Sannipataja, Agantuja (traumatic)',
      'Vataja Shotha: moves about, soft, reduces and increases, pain predominant',
      'Pittaja Shotha: hot, red/blue, burning, tender',
      'Kaphaja Shotha: heavy, cold, white, slow-growing, mild pain',
      'Raktaja: resembles Pittaja, associated with skin changes',
      'Sannipataja: mixed features, difficult to treat',
      'Agantuja: due to trauma, infection, external causes',
    ],
    shlokas: [],
    doshaDiscussion: [
      'Each dosha produces characteristic swelling pattern',
      'Combination dosha involvement creates complex presentations',
    ],
    treatmentPrinciples: [
      'Vataja: Snigdha (unctuous) + Swedana (fomentation)',
      'Pittaja: Sheeta (cold) + Tikta (bitter) treatment',
      'Kaphaja: Ruksha (dry) + Ushna (warm) + Tikshna (sharp) treatment',
      'Raktaja: bloodletting (Raktamokshana)',
      'Sannipataja: combined treatment approach',
    ],
    dietaryGuidelines: [],
    clinicalApplications: [
      'Edema management',
      'Inflammatory condition treatment',
      'Post-traumatic swelling management',
    ],
    topics: [],
  },
  {
    id: 'sutra_ch20',
    sthana: 'Sutra Sthana',
    chapterNumber: 20,
    name: 'Maharoga Adhyaya',
    english: 'Chapter on Major Diseases',
    summary: 'Classification and description of major diseases (Maha Roga) affecting different body systems. Covers Jwara (fever), Raktapitta (bleeding disorders), Shosha (wasting), Prameha (diabetes), Kushtha (skin diseases), Shotha (edema), Unmada (psychosis), and Apasmara (epilepsy).',
    keyConcepts: [
      'Eight major diseases: Jwara, Raktapitta, Shosha, Prameha, Kushtha, Shotha, Unmada, Apasmara',
      'Jwara is the foremost of all diseases - affects all dosha and dhatus',
      'Raktapitta: bleeding disorders with Pitta and Rakta vitiation',
      'Shosha: wasting/emaciation with Vata predominance',
      'Prameha: 20 types (10 Kaphaja, 4 Pittaja, 6 Vataja)',
      'Kushtha: 7 Mahakushtha (major) and 11 Kshudrakushtha (minor) skin diseases',
      'Shotha: swelling classified by dosha and etiology',
      'Unmada: psychosis/insanity - 5 types (Vataja, Pittaja, Kaphaja, Sannipataja, Agantuja)',
      'Apasmara: epilepsy - 4 types by dosha',
    ],
    shlokas: [],
    doshaDiscussion: [
      'Each major disease has specific dosha involvement',
      'Jwara involves all three dosha',
      'Prameha starts with Kapha, progresses to Pitta, then Vata',
    ],
    treatmentPrinciples: [
      'Disease-specific treatment protocols',
      'Progressive disease requires stage-appropriate treatment',
      'Sadhya (curable) vs Asadhya (incurable) assessment',
    ],
    dietaryGuidelines: [],
    clinicalApplications: [
      'Major disease classification for diagnosis',
      'Treatment protocol selection based on disease stage',
      'Prognosis assessment',
    ],
    topics: [
      { title: 'Eight Major Diseases', content: 'Jwara, Raktapitta, Shosha, Prameha, Kushtha, Shotha, Unmada, Apasmara - with full classification and treatment.' },
    ],
  },
  {
    id: 'sutra_ch22',
    sthana: 'Sutra Sthana',
    chapterNumber: 22,
    name: 'Langhanabrimhaniya Adhyaya',
    english: 'Chapter on Fasting and Nourishment',
    summary: 'Details Langhana (fasting/lightening therapy) and Brimhana (nourishing/hefting therapy) - their types, indications, and methods.',
    keyConcepts: [
      'Langhana: reduces excess Dosha, Ama, and body heaviness',
      'Types of Langhana: Upavasa (fasting), Pipasa (thirst), Atapa (sun exposure), Maruta (wind exposure), Vyayama (exercise), Pachana (digestive herbs)',
      'Brimhana: nourishes depleted tissues, increases body mass',
      'Brimhana measures: nutritious food, ghee, milk, meat soup, sleep, comfort',
      'Langhana indicated in: Ama, Kapha disorders, heaviness, obesity',
      'Brimhana indicated in: emaciation, debility, post-illness recovery, Vata disorders',
      'Ruksha (dry) Langhana vs Snigdha (unctuous) Langhana',
    ],
    shlokas: [],
    doshaDiscussion: [
      'Langhana pacifies Kapha and Ama',
      'Brimhana pacifies Vata and nourishes Dhatus',
      'Choice depends on predominant dosha and tissue status',
    ],
    treatmentPrinciples: [
      'Langhana for Ama and Kapha excess',
      'Brimhana for Dhatu Kshaya (tissue depletion)',
      'Rukshana (drying) for Kapha with Ama',
      'Snehana (oleation) for Vata without Ama',
    ],
    dietaryGuidelines: [
      'Langhana: light diet, thin gruel, warm water',
      'Brimhana: heavy, sweet, unctuous foods; milk, ghee, meat soup',
    ],
    clinicalApplications: [
      'Obesity management with Langhana',
      'Post-illness recovery with Brimhana',
      'Ama management before treatment',
      'Individualized approach based on Prakriti and disease',
    ],
    topics: [],
  },
  {
    id: 'sutra_ch27',
    sthana: 'Sutra Sthana',
    chapterNumber: 27,
    name: 'Annapanavidhi Adhyaya',
    english: 'Chapter on Food and Drink Classification',
    summary: 'Comprehensive classification of all food articles and drinks - their properties, actions, and therapeutic uses. Essential for dietary counseling.',
    keyConcepts: [
      'Food classified by source: Jangala (arid land), Anupa (marshy), Audaka (aquatic) animals',
      'Cereals: Shali rice, Shashtika rice, Yava (barley), Godhuma (wheat), with different properties',
      'Pulses: Mudga (green gram - best), Masha (black gram - heavy), Masura (lentil), etc.',
      'Vegetables: classified by taste and property',
      'Fruits: Draksha (grapes - best), Amalaka (best for health), etc.',
      'Milk types: Cow (best for health), Goat (for respiratory), Buffalo (heavy), Camel, Mare, etc.',
      'Ghee: best Sneha, enhances memory, intelligence, digestion',
      'Honey: best for Kapha, not to be heated',
      'Water types: rain water (best), river, well, lake - with different properties',
      'Six Rasa in food and their effects on dosha',
    ],
    shlokas: [],
    doshaDiscussion: [
      'Madhura (sweet): nourishes, increases Kapha, pacifies Vata-Pitta',
      'Amla (sour): stimulates Agni, increases Pitta-Kapha, pacifies Vata',
      'Lavana (salt): increases Pitta-Kapha, pacifies Vata in small amounts',
      'Tikta (bitter): reduces Kapha-Pitta, does not increase Vata significantly',
      'Katu (pungent): increases Vata-Pitta, reduces Kapha, stimulates Agni',
      'Kashaya (astringent): reduces Pitta-Kapha, can increase Vata',
    ],
    treatmentPrinciples: [
      'Diet based on disease, season, Prakriti, and Agni',
      'Specific food combinations to avoid (Viruddha Ahara)',
      'Therapeutic use of individual food items',
    ],
    dietaryGuidelines: [
      'Mudga (green gram): best pulse, light, suitable for all',
      'Amalaka: best fruit, Rasayana, balances all three dosha',
      'Ghrita: best Sneha, daily use recommended',
      'Madhu (honey): best for Kapha, never heat it',
      'Saindhava (rock salt): best salt, least harmful',
      'Cow milk: nourishing, Rasayana, good for all',
    ],
    clinicalApplications: [
      'Dietary counseling for all diseases',
      'Food-drug interaction management',
      'Prakriti-based diet planning',
      'Seasonal dietary adjustments',
    ],
    topics: [
      { title: 'Food Classification', content: 'By source, taste, property, and therapeutic action.' },
      { title: 'Therapeutic Foods', content: 'Specific foods for specific conditions - milk for Vata, ghee for Pitta, honey for Kapha.' },
    ],
  },
  {
    id: 'sutra_ch28',
    sthana: 'Sutra Sthana',
    chapterNumber: 28,
    name: 'Vividhashitapitiya Adhyaya',
    english: 'Chapter on Various Foods and Drinks',
    summary: 'Further details on food properties, incompatible food combinations (Viruddha Ahara), and their consequences. Critical for understanding food-as-medicine principles.',
    keyConcepts: [
      'Viruddha Ahara (incompatible food): causes skin diseases, blindness, insanity, edema, fistula, ascites, toxicity',
      'Examples: fish + milk, honey + ghee (equal quantities), honey heated',
      'Food quality depends on Desha (place), Kala (season), Agni (digestive fire)',
      'Eight factors for food assessment: Prakriti (nature), Karana (processing), Samyoga (combination), Rashi (quantity), Desha (place), Kala (time), Upayoga (usage), Upayokta (consumer)',
      'Proper eating habits: eat warm, unctuous, in proper quantity, after previous meal digested',
      'Eat in calm state, not too fast or too slow, focus on food',
    ],
    shlokas: [],
    doshaDiscussion: [
      'Viruddha Ahara creates Ama and dosha vitiation',
      'Food combinations can vitiate specific dosha',
    ],
    treatmentPrinciples: [
      'Avoid Viruddha Ahara to prevent disease',
      'Food preparation method affects properties',
      'Individual food assessment needed',
    ],
    dietaryGuidelines: [
      'Never eat incompatible combinations',
      'Honey must never be heated or mixed with hot substances',
      'Fish and milk should not be combined',
      'Eat at proper time with proper attention',
    ],
    clinicalApplications: [
      'Food allergy and intolerance management',
      'Dietary disease prevention',
      'Understanding food-drug interactions',
    ],
    topics: [
      { title: 'Viruddha Ahara', content: '18 types of food incompatibility with examples and consequences.' },
    ],
  },
]

// Helper function to search Sutra Sthana
export function searchSutraSthana(query: string): CharakChapter[] {
  const q = query.toLowerCase()
  return SUTRA_STHANA.filter(ch =>
    ch.name.toLowerCase().includes(q) ||
    ch.english.toLowerCase().includes(q) ||
    ch.summary.toLowerCase().includes(q) ||
    ch.keyConcepts.some(c => c.toLowerCase().includes(q)) ||
    ch.clinicalApplications.some(a => a.toLowerCase().includes(q)) ||
    ch.topics.some(t => t.title.toLowerCase().includes(q) || t.content.toLowerCase().includes(q))
  )
}

export function getSutraChapterByNumber(num: number): CharakChapter | undefined {
  return SUTRA_STHANA.find(ch => ch.chapterNumber === num)
}
